# Generated by Django 5.1.15 on 2026-06-20 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('operations', 'Operations'), ('support', 'Customer Support'), ('finance', 'Finance'), ('logistics', 'Logistics')], default='operations', max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('can_verify_payments', models.BooleanField(default=True)),
                ('can_manage_orders', models.BooleanField(default=True)),
                ('can_manage_customers', models.BooleanField(default=False)),
                ('can_manage_vendors', models.BooleanField(default=False)),
                ('can_manage_riders', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_profiles',
            },
        ),
    ]
