# Generated by Django 5.1.15 on 2026-06-20 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('new_order', 'New Order'), ('low_stock', 'Low Stock Alert'), ('delivery_assigned', 'Delivery Assigned'), ('vendor_registered', 'Vendor Registered'), ('vendor_approved', 'Vendor Approved'), ('ticket_reply', 'Support Ticket Reply'), ('ticket_resolved', 'Ticket Resolved'), ('withdrawal_processed', 'Withdrawal Processed'), ('large_order', 'Large Order Alert'), ('general', 'General')], default='general', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('icon', models.CharField(blank=True, default='bi-bell', max_length=50)),
                ('color', models.CharField(blank=True, default='primary', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
